# Generated by Django 2.2.4 on 2019-08-15 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('num', models.PositiveIntegerField()),
                ('certificate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='exam.Certificate')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_num', models.PositiveIntegerField()),
                ('contents', models.CharField(max_length=200)),
                ('answer', models.PositiveIntegerField()),
                ('img', models.ImageField(blank=True, upload_to='questions/%Y/%m/%d')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='exam.Test')),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_num', models.PositiveIntegerField()),
                ('contents', models.CharField(max_length=200)),
                ('img', models.ImageField(blank=True, upload_to='choices/%Y/%m/%d')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='exam.Question')),
            ],
        ),
    ]
