# Generated by Django 2.2.4 on 2019-08-19 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0003_report_submitquestion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submitquestion',
            name='answer',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
